### PR TITLE
Fix actions

### PR DESCRIPTION
**Pull request by arthuro555**
Try to fix the github actions

### CODE REVIEW

**Comment by TheGemDev** [comment]
For some reason it's still failing

**Comment by arthuro555** [comment]
According to the logs, this was due to a warning and it refuses to compile a production build of an app with warnings. Merging master should do the trick.

**Comment by arthuro555** [comment]
Ok, apparently the action is wrongly set up, there should be a service account in the github secrets of the repository but there isn't. I can't fix that as only the owner can access github secrets (because they are secret).

**Comment by arthuro555** [comment]
See https://github.com/FirebaseExtended/action-hosting-deploy/blob/main/docs/service-account.md to set up the service account.

**Pull request closed without merging**
